spring:
  application:
    name: Eticketia
  profiles:
    active: '@activatedProperties@'
  docker:
    compose:
      enabled: true
      lifecycle-management: start_and_stop
  threads:
    virtual:
      enabled: true

server:
  http2:
    enabled: true

eticketia:
  banner:
    buildName: '@artifactId@_@project.version@'
