spring:
  application:
    name: Eticketia
  profiles:
    active: '@activatedProperties@'
  docker:
    compose:
      enabled: true
      lifecycle-management: start_and_stop
  threads:
    virtual:
      enabled: true
  server:
    multipart:
      enabled: true
      max-file-sie: 20MB
      max-request-size: 20MB
      file-size-threshold: 1MB

server:
  http2:
    enabled: true

eticketia:
  banner:
    buildName: '@artifactId@_@project.version@'
