spring:
  docker:
    compose:
      enabled: true
      file: 'compose-dev.yaml'
      lifecycle-management: start_and_stop

logging:
  config: 'classpath:log4j2-dev.xml'

eticketia:
  banner:
    buildName: '[@activatedProperties@ mode] @artifactId@_@project.version@'